### ISSUE TITLE
Boto3 Store is untested code

### ISSUE THREAD

**Issue by siboehm** [data-engineering-collective/minimalkv#10]
In SimpleKV the Boto3 store was merged while the CI had been down for months: https://github.com/mbr/simplekv/pull/106

So there was never a successful test-run on the CI. I spent an hour on it but couldn't figure out how to get it to connect to a Minio instance without bigger changes to the code. This is due to the client being created implicitly (contrary to explicitly like in the Boto store). I couldn't find a way to point the client to a local endpoint without modifying the global `~/.aws/config` file. 

The `boto` store still works, but the `boto` library hasn't seen any updates since 2018, so we should move to `boto3` at some point definitely.

**Comment by simonbohnen** [comment]
The tests for the `Boto3Store` are running, see e.g. [here](https://github.com/data-engineering-collective/minimalkv/actions/runs/3345258665/jobs/5540555389#step:6:685) for failure vs [here](https://github.com/data-engineering-collective/minimalkv/actions/runs/3368803194/jobs/5587754632) for passing tests.

**Comment by simonbohnen** [comment]
@xhochy could you close this?
