### ISSUE TITLE
Ambivalent license

### ISSUE THREAD

**Issue by johanols** [data-engineering-collective/minimalkv#124]
In the `README.rst` it is stated that the `minimalkv` license is MIT. However, the `LICENSE` file itself looks like the BSD-3 license. So which license is `minimalkv` distributed under? Would you mind making this a bit more clear?

Thank you for a great software package!

**Comment by xhochy** [comment]
`BSD-3-Clause` is correct: https://github.com/data-engineering-collective/minimalkv/pull/127
